### ISSUE TITLE
Assign other users to card

### ISSUE THREAD

**Issue by jcf0419** [Ho-Wan/vscode-trello-viewer#2]
Would be nice to assign users to a card task.

**Comment by jcf0419** [comment]
Hey - would love to get involved with contributions.. I need to spend some time on learning how to dev extensions in vs code. - let me know if you are open to help.

**Comment by Ho-Wan** [comment]
@jcf0419 Hi, you are welcome to get involved and help by contributing, thanks!

**Comment by Ho-Wan** [comment]
I think assigning yourself to the card would be a good feature to start with. 

Assigning someone else to a card would be harder, but could be a follow on feature.

**Comment by jcf0419** [comment]
Great place to start!

**Comment by Ho-Wan** [comment]
Assign self to card feature implemented in v0.5.0.

**Comment by ho-wan** [comment]
Assign any user to card implemented in v0.6.0.
