### ISSUE TITLE
Right click card - move card to list options

### ISSUE THREAD

**Issue by jcf0419** [Ho-Wan/vscode-trello-viewer#27]
Would be nice to see move card to an existing list within an existing board.. maybe even move to another board. 

Other ideas would be:
Move list from one board to another including all cards within the given list
Move all cards to another existing list
Move all cards into new list by specified board

**Comment by ho-wan** [comment]
Move card to existing list on same board functionality added in v0.6.0. Closing this for now as this is the main feature required.
